site_name: Academic Notion
site_description: Make Notion a better alternative to Zotero by seamlessly integrate academic research into your Notion workflow
site_url: https://hamsternotion.com

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Terms of Use: terms_of_use.md
  - Blog:
     - blog/index.md
     - Tags: tags.md

plugins:
  - search
  - tags:
      tags_file: ./tags.md
  - blog
